#!/bin/bash
#
# Gemeinschaft 5
# System add-on: Advanced debugging tools
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GSE file for details.
#

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GSE_DIR}" == x"" ]] && exit 1

GSE_ADDON_NAME="`basename $0`"
GSE_ADDON_DESCRIPTION="Install advanced debugging tools"
GSE_ADDON_VERSION="0.1"

case "$1" in
	install)
		aptitude -q2 update
		aptitude -yy -q2 install tshark kdump-tools
		"${GSE_DIR_NORMALIZED}/bin/gs-enforce-security.sh" | grep -Ev retained | grep -Ev "no changes" | grep -Ev "nor referent has been changed"
		;;

	remove)
		aptitude -yy -q2 purge tshark kdump-tools
		;;
	
	update)
		bash $0 install
		;;

	version)
		echo -e "${GSE_ADDON_VERSION}"
		;;
	
	*)
		echo -e "${GSE_ADDON_NAME} (v${GSE_ADDON_VERSION})\n\t${GSE_ADDON_DESCRIPTION}"
		;;
esac

exit 0
