#!/bin/bash
#
# Gemeinschaft 5
# System add-on: FHEM Home Automation Server
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GSE file for details.
#

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GSE_DIR}" == x"" ]] && exit 1

GSE_ADDON_NAME="`basename $0`"
GSE_ADDON_DESCRIPTION="FHEM Home Automation Server"
GSE_ADDON_VERSION="5.4"

case "$1" in
	install)
		aptitude -q2 update
		aptitude -yy -q2 install perl libdevice-serialport-perl libio-socket-ssl-perl libwww-perl
		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O "http://fhem.de/fhem-${GSE_ADDON_VERSION}.deb"
		dpkg -i fhem-${GSE_ADDON_VERSION}.deb
		if [ $? != 0 ]; then
			rm -rf fhem-${GSE_ADDON_VERSION}.deb
			exit 1
		fi
		rm -rf fhem-${GSE_ADDON_VERSION}.deb
		aptitude -yy -q2 install -f
		cd - 2>&1>/dev/null
				
		# update FHEM config
		FHEM_STATUS="`grep "fhem-gemeinschaft.cfg" /opt/fhem/fhem.cfg`"
		if [ "${FHEM_STATUS}" == "" ]; then
			echo "include /etc/opt/fhem/fhem-gemeinschaft.cfg" >> /opt/fhem/fhem.cfg
			service fhem stop && service fhem start
		fi
		;;

	remove)
		aptitude -yy -q2 purge fhem
		echo $?
		;;

	update)
		$0 install
		;;

	version)
		echo -e "${GSE_ADDON_VERSION}"
		;;
	
	*)
		echo -e "${GSE_ADDON_NAME} (v${GSE_ADDON_VERSION})\n\t${GSE_ADDON_DESCRIPTION}"
		;;
esac

exit 0
