#!/bin/bash
#
# Gemeinschaft 5
# System add-on: FreeSwitch sounds 16kHz
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GBE file for details.
#

# General settings
[ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GS_DIR}" == x"" ]] && exit 1

GS_SYSADDON_NAME="`basename $0`"
GS_SYSADDON_DESCRIPTION="FreeSwitch high quality sound files (16 kHz)"

case "$1" in
	install)
		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O "http://files.freeswitch.org/freeswitch-sounds-en-us-callie-16000-1.0.22.tar.gz" -O "http://files.freeswitch.org/freeswitch-sounds-music-16000-1.0.8.tar.gz"
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec tar xfz {} -C /usr/share/freeswitch/sounds \;
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec rm {} \;
		cd - 2>&1>/dev/null
		;;

	remove)
		FILELIST="`find /usr/share/freeswitch/sounds -name '16000' -type d`"
		rm -rf ${FILELIST}
		;;
	
	*)
		echo -e "${GS_SYSADDON_NAME}\n\t${GS_SYSADDON_DESCRIPTION}"
		;;
esac
