#!/bin/bash
#
# Gemeinschaft 5
# System add-on: FreeSwitch G.729 codec
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GSE file for details.
#

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GSE_DIR}" == x"" ]] && exit 1

GSE_ADDON_NAME="`basename $0`"
GSE_ADDON_DESCRIPTION="FreeSwitch commercial G729 codec installation and license activation"
VERSION="194"

case "$1" in
	install)
		if [ ! -e /usr/bin/unzip ]; then
			aptitude -q2 update
			aptitude -yy -q2 install unzip
			[[ $? != 0 || ! -e /usr/bin/unzip ]] && exit 1
		fi

		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O -O "http://files.freeswitch.org/g729/fsg729-${VERSION}-installer"
		FILE_FORMAT="`file fsg729-${VERSION}-installer | grep "data"`"
		[ x"${FILE_FORMAT}" == x"" ] && exit 1
		chmod 755 "fsg729-${VERSION}-installer"

		./fsg729-${VERSION}-installer && rm -f ./fsg729-${VERSION}-installer
		if [[ ! -e /opt/freeswitch/bin/validator || ! -e /usr/lib/freeswitch/mod/mod_com_g729.so || ! -e /usr/sbin/freeswitch_licence_server ]]; then
			rm -f /opt/freeswitch/bin/validator /usr/lib/freeswitch/mod/mod_com_g729.so /usr/sbin/freeswitch_licence_server
			exit 1
		fi
		cd - 2>&1>/dev/null

		if [ ! -e ./licences.zip ]; then
			/opt/freeswitch/bin/validator
			if [[ $? != 0 || ! -e ./licences.zip ]]; then
				rm -f /opt/freeswitch/bin/validator /usr/lib/freeswitch/mod/mod_com_g729.so /usr/sbin/freeswitch_licence_server
				exit 1
			fi
		fi

		unzip ./licences.zip -d /etc/freeswitch/
		if [[ $? != 0 ]]; then
			echo "Your license archive file in `pwd`/licences.zip could not be extracted, it might be corrupted."
			exit 1
		else
			echo "Your license archive file has been saved to `pwd`/licenses.zip, you may want to backup it!"
		fi

		"${GSE_DIR_NORMALIZED}/bin/gs-enforce-security.sh" | grep -Ev retained | grep -Ev "no changes" | grep -Ev "nor referent has been changed"

		fs_cli -x "unload mod_g729"
		fs_cli -x "load mod_com_g729"
		fs_cli -x "g729_info"
		
		G729_RESULT="`fs_cli -x g729_available`"
		
		if [ "${G729_RESULT}" != true ]; then
			echo -e "\n\nCommercial G729 installation COMPLETE but activation in FreeSwitch FAILED !\n\nTo enable the codec please add mod_com_g729 to freeswitch.xml and remove mod_g729 to avoid conflicts.\n\n"
		else
			echo -e "\n\nCommercial G729 installation & activation COMPLETE !\n\nTo keep the codec enabled after reboot please add mod_com_g729 to freeswitch.xml and remove mod_g729 to avoid conflicts.\n\n"
	 	fi

		cd - 2>&1>/dev/null
		;;

	remove)
		echo -e "\n\nThis will only remove G729 commercial activation tools and G729 commercial module.\nYour license file will not be touched!\n\n"
		fs_cli -x "unload mod_com_g729"
		killall freeswitch_licence_server
		rm -f /opt/freeswitch/bin/validator /usr/lib/freeswitch/mod/mod_com_g729.so /usr/sbin/freeswitch_licence_server
		
		echo -e "\nPlease make sure to remove mod_com_g729 from freeswitch.xml to avoid any issues during next boot.\n"
		;;

	update)
		$0 remove >/dev/null

		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O -O "http://files.freeswitch.org/g729/fsg729-${VERSION}-installer"
		FILE_FORMAT="`file fsg729-${VERSION}-installer | grep "data"`"
		[ x"${FILE_FORMAT}" == x"" ] && exit 1
		chmod 755 "fsg729-${VERSION}-installer"

		./fsg729-${VERSION}-installer && rm -f ./fsg729-${VERSION}-installer
		if [[ ! -e /opt/freeswitch/bin/validator || ! -e /usr/lib/freeswitch/mod/mod_com_g729.so || ! -e /usr/sbin/freeswitch_licence_server ]]; then
			rm -f /opt/freeswitch/bin/validator /usr/lib/freeswitch/mod/mod_com_g729.so /usr/sbin/freeswitch_licence_server
			exit 1
		fi
		cd - 2>&1>/dev/null
		;;

	version)
		echo -e "${VERSION}"
		;;
	
	*)
		echo -e "${GSE_ADDON_NAME}\n\t${GSE_ADDON_DESCRIPTION} (v${VERSION})"
		;;
esac

exit 0
