#!/bin/bash
#
# Gemeinschaft 5
# System add-on: FreeSwitch music 16kHz
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GSE file for details.
#

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GSE_DIR}" == x"" ]] && exit 1

GSE_ADDON_NAME="`basename $0`"
GSE_ADDON_DESCRIPTION="FreeSwitch HQ music files (16 kHz)"
GSE_ADDON_VERSION="1.0.8"

case "$1" in
	install)
		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O -O "http://files.freeswitch.org/freeswitch-sounds-music-16000-${GSE_ADDON_VERSION}.tar.gz"
		FILE_FORMAT="`file freeswitch-sounds-music-16000-${GSE_ADDON_VERSION}.tar.gz | grep "gzip compressed data"`"
		[ x"${FILE_FORMAT}" == x"" ] && exit 1
		mkdir -p /usr/share/freeswitch/sounds
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec tar xfz {} -C /usr/share/freeswitch/sounds \;
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec rm {} \;
		cd - 2>&1>/dev/null
		;;

	remove)
		FILELIST="`find /usr/share/freeswitch/sounds/en /usr/share/freeswitch/sounds/music -name '16000' -type d`"
		rm -rf ${FILELIST}
		;;
	
	update)
		$0 remove
		$0 install
		;;

	version)
		echo -e "${GSE_ADDON_VERSION}"
		;;

	*)
		echo -e "${GSE_ADDON_NAME} (v${GSE_ADDON_VERSION})\n\t${GSE_ADDON_DESCRIPTION}"
		;;
esac

exit 0
