#!/bin/bash
#
# Gemeinschaft 5
# System add-on: FreeSwitch sounds 8kHz
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GSE file for details.
#

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GSE_DIR}" == x"" ]] && exit 1

GSE_ADDON_NAME="`basename $0`"
GSE_ADDON_DESCRIPTION="FreeSwitch sound files in english language (Human voice: Callie)"
VERSION="1.0.24"

case "$1" in
	install)
		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O "http://files.freeswitch.org/freeswitch-sounds-en-us-callie-8000-${VERSION}.tar.gz"
		[[ ! -e freeswitch-sounds-en-us-callie-8000-${VERSION}.tar.gz ]] && exit 1
		mkdir -p /usr/share/freeswitch/sounds
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec tar xfz {} -C /usr/share/freeswitch/sounds \;
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec rm {} \;
		cd - 2>&1>/dev/null
		;;

	remove)
		FILELIST="`find /usr/share/freeswitch/sounds/en/us/callie -name '8000' -type d`"
		rm -rf ${FILELIST}
		;;
	
	update)
		$0 remove
		$0 install
		;;

	version)
		echo -e "${VERSION}"
		;;

	*)
		echo -e "${GSE_ADDON_NAME}\n\t${GSE_ADDON_DESCRIPTION} (v${VERSION})"
		;;
esac

exit 0
