#!/bin/bash
#
# Gemeinschaft 5
# System add-on: German FreeSwitch sounds 8kHz
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GSE file for details.
#

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GSE_DIR}" == x"" ]] && exit 1

GSE_ADDON_NAME="`basename $0`"
GSE_ADDON_DESCRIPTION="FreeSwitch HQ sound files in german language (via Google TTS)"
VOICE="google"
FREQ="16000"
LANG="de"
VERSION="1.0.2"

case "$1" in
	install)
		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O "http://repo.amooma.de/static/freeswitch/freeswitch-sounds-${LANG}-tts-${VOICE}-${FREQ}-${VERSION}.tar.gz"
		[[ ! -e freeswitch-sounds-${LANG}-tts-${VOICE}-${FREQ}-${VERSION}.tar.gz ]] && exit 1
		mkdir -p /usr/share/freeswitch/sounds
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec tar xfz {} -C /usr/share/freeswitch/sounds \;
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec rm {} \;
		cd - 2>&1>/dev/null
		;;

	remove)
		FILELIST="`find /usr/share/freeswitch/sounds/${LANG}/tts/${VOICE} -name '${FREQ}' -type d`"
		rm -rf ${FILELIST}
		;;
	
	update)
		$0 remove
		$0 install
		;;

	version)
		echo -e "${VERSION}"
		;;

	*)
		echo -e "${GSE_ADDON_NAME}\n\t${GSE_ADDON_DESCRIPTION} (v${VERSION})"
		;;
esac

exit 0
