#!/bin/bash
#
# Gemeinschaft 5
# System add-on: FreeSwitch sounds 16kHz
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GSE file for details.
#

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GSE_DIR}" == x"" ]] && exit 1

GSE_ADDON_NAME="`basename $0`"
GSE_ADDON_DESCRIPTION="FreeSwitch HQ sound files in english language (Human voice: Callie)"

case "$1" in
	install)
		cd /usr/local/src
		curl --retry 5 --retry-delay 3 -O "http://files.freeswitch.org/freeswitch-sounds-en-us-callie-16000-1.0.24.tar.gz"
		[[ ! -e freeswitch-sounds-en-us-callie-16000-1.0.24.tar.gz ]] && exit 1
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec tar xfz {} -C /usr/share/freeswitch/sounds \;
		find /usr/local/src -name 'freeswitch-*.tar.gz' -type f -exec rm {} \;
		cd - 2>&1>/dev/null
		exit 0
		;;

	remove)
		FILELIST="`find /usr/share/freeswitch/sounds/en/us/callie -name '16000' -type d`"
		rm -rf ${FILELIST}
		;;
	
	*)
		echo -e "${GSE_ADDON_NAME}\n\t${GSE_ADDON_DESCRIPTION}"
		;;
esac
