#!/bin/bash
#
# Gemeinschaft 5
# System add-on: MonAMI Asterisk Manger Interface Emulator
#
# Copyright (c) 2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GBE file for details.
#

# General settings
[ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"
[[ x"${GS_DIR}" == x"" ]] && exit 1

GS_SYSADDON_NAME="`basename $0`"
GS_SYSADDON_DESCRIPTION="Enable MonAMI Asterisk Manger Interface Emulator"

case "$1" in
	install)
		update-rc.d mon_ami defaults
		[[ `service mon_ami status` != 0 ]] && service mon_ami start
		;;

	remove)
		[[ `service mon_ami status` ]] && service mon_ami stop
		update-rc.d mon_ami remove
		;;
	
	*)
		echo -e "${GS_SYSADDON_NAME}\n\t${GS_SYSADDON_DESCRIPTION}"
		;;
esac
