#! /bin/bash
### BEGIN INIT INFO
# Provides:          gemeinschaft-runtime-init
# Required-Start:    hostname haveged
# Required-Stop:     
# X-Start-Before:    apache2 freeswitch mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Updates certain configurations after reboot
# Description:       Updates certain configurations after reboot to comply with current network settings
### END INIT INFO

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"

# Enforce root rights
#
if [[ ${EUID} -ne 0 ]];
	then
	echo "ERROR: `basename $0` needs to be run as root. Aborting ..."
	exit 1
fi

case "$1" in
start)
	FQDN="`hostname -f`";
	IPS="`hostname -I`"

	# Create SSL certificate for current Full Qualified Domain Name
	if [[
		! -e /etc/ssl/private/${FQDN}.key ||
		! -e /etc/ssl/certs/${FQDN}.crt
		]]; then

		# Make sure both files are not existing
		rm -rf /etc/ssl/private/${FQDN}.key /etc/ssl/certs/${FQDN}.crt

		echo "Generating SSL certificate for ${FQDN} ..."
		openssl req -newkey rsa:2048 -x509 -days 3650 -nodes -out /etc/ssl/certs/${FQDN}.crt -keyout /etc/ssl/private/${FQDN}.key -subj "/C=DE/ST=Rhineland-Palatinate/L=Neuwied/O=AMOOMA GmbH/OU=Self-generated certificate for Gemeinschaft/CN=${FQDN}"
		update-ca-certificates

		ln -sf /etc/ssl/private/${FQDN}.key /etc/ssl/gemeinschaft.key
		ln -sf /etc/ssl/certs/${FQDN}.crt /etc/ssl/gemeinschaft.crt
	fi

	# Check for available system update
	if [[ -d "${GS_DIR}.update" ]];
		then
		echo "*** Found update files, processing update tasks now ..."
		"${GSE_DIR_NORMALIZED}/bin/gs-update.sh" --force-update
	fi

	;;
*)
	# nothing to do
	;;
esac
