#! /bin/bash
### BEGIN INIT INFO
# Provides:          gemeinschaft-prompt
# Required-Start:    $local_fs $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gemeinschaft Login screen
# Description:       
### END INIT INFO
#
# Create customized login screen for Gemeinschaft 5
#

# General settings
[ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"

# Enforce root rights
#
if [[ ${EUID} -ne 0 ]];
	then
	echo "ERROR: `basename $0` needs to be run as root. Aborting ..."
	exit 1
fi

# Check for live status
#
if [[ x`cat /proc/cmdline | grep boot=live` != x"" ]]
	then
	LIVE=true
else
	LIVE=false
fi

# Get network configuration details
#
sleep 1
IPS="`/bin/hostname -I`"
FQDN="`/bin/hostname -f`"

#
# Write login screen to /etc/issue
#

echo "
***      _____                                               _____
***     (.---.)                 GEMEINSCHAFT 5              (.---.)
***      /:::\\\ _.-----------------------------------------._ /:::\\\ 
***      -----                                               -----
***     Version: ${GS_VERSION} #${GS_BUILDNAME}
***    -------------------------------------------------------------
***
***     You have to configure Gemeinschaft with a web browser:
***" > /etc/issue

if [[ -z "${IPS}" ]]; then
	echo "***     - FAILED network configuration detection -" >> /etc/issue
	echo "***" >> /etc/issue
else
	for ADDRESS in ${FQDN} ${IPS}
	do
		[[ ${ADDRESS} =~ "localhost" ]] && echo "***" >> /etc/issue && continue
		[[ ${ADDRESS} =~ ":" ]] && ADDRESS="["${ADDRESS}"]" 
		echo "***     http://${ADDRESS}" >> /etc/issue
	done
fi

echo "***
***
***
***" >> /etc/issue

if [[ ${LIVE} == true ]]
	then
	echo "***     DEMO LIVE SYSTEM - ALL CHANGES WILL BE LOST AFTER A REBOOT!" >> /etc/issue
	echo "***" >> /etc/issue
	echo "***     LOGIN        : gsmaster" >> /etc/issue
    echo "***     PASSWORD     : `cat /home/gsmaster/.password`" >> /etc/issue
else
	echo "***" >> /etc/issue
	echo "***" >> /etc/issue
	echo "***" >> /etc/issue
	echo "***" >> /etc/issue
fi

echo "***     Documentation: Visit http://amooma.de/gemeinschaft/gs5
***    _____________________________________________________________
***          brought to you by AMOOMA GmbH  - http://amooma.de
" >> /etc/issue


#
# Write motd and issue.net
#
echo "Welcome to GEMEINSCHAFT ${GS_VERSION} #${GS_BUILDNAME}" > /etc/issue.net
echo "
***   Welcome to GEMEINSCHAFT ${GS_VERSION} #${GS_BUILDNAME}
***
***   Need help with Gemeinschaft? We have an excellent free mailinglist
***   and offer the best support and consulting money can buy. Have a
***   look at http://amooma.de/gemeinschaft/gs5 for more information.
***
" > /etc/motd
