#! /bin/bash
### BEGIN INIT INFO
# Provides:          gemeinschaft-runtime-helper
# Required-Start:    mysql apache2 gemeinschaft-runtime-init
# Required-Stop:     
# X-Start-Before:    freeswitch gemeinschaft-runtime-init-post
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Do some preparations before FreeSwitch
# Description:       Do some preparations before FreeSwitch
### END INIT INFO

# General settings
[ -e /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"

# Enforce root rights
#
if [[ ${EUID} -ne 0 ]];
	then
	echo "ERROR: `basename $0` needs to be run as root. Aborting ..."
	exit 1
fi

case "$1" in
start)

	# Read GSE version from Git repo
	#
	cd "${GSE_DIR_NORMALIZED}"
	GSE_LATEST_VERSION="`git for-each-ref --format '%(refname)' refs/tags | cut -d "/" -f 3 | tail -n1`"
	GSE_CURRENT_REVISION="`git rev-parse --abbrev-ref HEAD`"
	cd - 2>&1>/dev/null

	if [[ "${GSE_CURRENT_REVISION}" == "master" || "${GSE_CURRENT_REVISION}" == "HEAD" ]]; then
		GSE_VERSION_EXTRACTED="${GSE_LATEST_VERSION}"
	else
		GSE_VERSION_MINOR="`echo ${GSE_LATEST_VERSION##*.} | sed -e 's/^.*\([0-9]\)$/\1/'`"
		GSE_VERSION_NEXT="`expr ${GSE_VERSION_MINOR} + 1`"
		GSE_VERSION_EXTRACTED="${GSE_LATEST_VERSION%${GSE_VERSION_MINOR}}${GSE_VERSION_NEXT}-${GSE_BRANCH}"
	fi

	# Read GS version from Git repo
	#
	cd "${GS_DIR_NORMALIZED}"
	GS_LATEST_VERSION="`git for-each-ref --format '%(refname)' refs/tags | cut -d "/" -f 3 | tail -n1`"
	GS_CURRENT_REVISION="`git rev-parse --abbrev-ref HEAD`"
	cd - 2>&1>/dev/null

	if [[ "${GS_CURRENT_REVISION}" == "master" || "${GS_CURRENT_REVISION}" == "HEAD" ]]; then
		GS_VERSION_EXTRACTED="${GS_LATEST_VERSION}"
	else
		GS_VERSION_MINOR="`echo ${GS_LATEST_VERSION##*.} | sed -e 's/^.*\([0-9]\)$/\1/'`"
		GS_VERSION_NEXT="`expr ${GS_VERSION_MINOR} + 1`"
		GS_VERSION_EXTRACTED="${GS_LATEST_VERSION%${GS_VERSION_MINOR}}${GS_VERSION_NEXT}-${GS_BRANCH}"
	fi

	# Update local config file
	#
	if [[ "${GSE_VERSION_EXTRACTED}" != "${GSE_VERSION}" || "${GS_VERSION_EXTRACTED}" != "${GS_VERSION}" ]]; then
		GSE_VERSION="${GSE_VERSION_EXTRACTED}"
		GS_VERSION="${GS_VERSION_EXTRACTED}"
		mv -f /etc/gemeinschaft/system.conf /etc/gemeinschaft/system.conf.bak
		egrep -Ev "(^GSE_VERSION=|^GS_VERSION=)" /etc/gemeinschaft/system.conf.bak > /etc/gemeinschaft/system.conf
		echo "GSE_VERSION=\"${GSE_VERSION}\"" >> /etc/gemeinschaft/system.conf
		echo "GS_VERSION=\"${GS_VERSION}\"" >> /etc/gemeinschaft/system.conf
	fi

	# Heat up the cache
	#
	echo "Preparing Gemeinschaft Caching ..."
	su - ${GSE_USER} -c "cd ${GS_DIR_NORMALIZED}; RAILS_ENV=$RAILS_ENV rake heater:preheat"

	;;
*)
	# nothing to do
	;;
esac
